name: gendiff-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies with uv
        run: |
          pip install uv
          uv pip install --system --no-deps .
          uv pip install --system --deps

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Pytest with coverage
        run: uv run pytest
